version: '3.8'

services:
  alisto-api:
    build:
      context: ./Alisto.Api
      dockerfile: Dockerfile
      target: build
    container_name: alisto-api-local

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000
      - ConnectionStrings__DB=${DATABASE_URL}
      - JwtSettings__Issuer=${JWT_ISSUER}
    ports:
      - "7000:7000"
    volumes:
      - ./Alisto.Api:/src
      - /src/bin
      - /src/obj
    restart: unless-stopped 